name: CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
        with:
          php_version: 8.1

# php version is ignored, php-cs does not run on 8.1
#      - name: coding style
#        uses: php-actions/composer@v6
#        with:
#          php_version: 8.0
#          command: cs-check

      - name: static code analysis
        uses: php-actions/composer@v6
        with:
          php_version: 8.1
          php_extensions: mongodb
          command: analyse

      - name: unit tests
        uses: php-actions/composer@v6
        with:
          php_version: 8.1
          php_extensions: mongodb
          command: test-unit